
package it.uniroma1.generatedsource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSInterface", targetNamespace = "http://soapws.uniroma1.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.uniroma1.generatedsource.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookDetails", targetNamespace = "http://soapws.uniroma1.it/", className = "it.uniroma1.generatedsource.GetBookDetails")
    @ResponseWrapper(localName = "getBookDetailsResponse", targetNamespace = "http://soapws.uniroma1.it/", className = "it.uniroma1.generatedsource.GetBookDetailsResponse")
    public Book getBookDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeliveryDate", targetNamespace = "http://soapws.uniroma1.it/", className = "it.uniroma1.generatedsource.GetDeliveryDate")
    @ResponseWrapper(localName = "getDeliveryDateResponse", targetNamespace = "http://soapws.uniroma1.it/", className = "it.uniroma1.generatedsource.GetDeliveryDateResponse")
    public String getDeliveryDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
